data_json_location = {
  "coord": {
    "lon": 37.6175,
    "lat": 55.7504
  },
  "weather": [
    {
      "id": 800,
      "main": "Clear",
      "description": "ясно",
      "icon": "01n"
    }
  ],
  "base": "stations",
  "main": {
    "temp": -1.68,
    "feels_like": -4.88,
    "temp_min": -1.85,
    "temp_max": -1.2,
    "pressure": 1030,
    "humidity": 94,
    "sea_level": 1030,
    "grnd_level": 1009
  },
  "visibility": 10000,
  "wind": {
    "speed": 2.38,
    "deg": 270,
    "gust": 5.84
  },
  "clouds": {
    "all": 6
  },
  "dt": 1732467228,
  "sys": {
    "type": 1,
    "id": 9027,
    "country": "RU",
    "sunrise": 1732425787,
    "sunset": 1732453790
  },
  "timezone": 10800,
  "id": 524901,
  "name": "Москва",
  "cod": 200
}

data_json_list_locations = [
  {
    "name": "London",
    "local_names": {
      "st": "London",
      "fr": "Londres",
      "is": "London",
      "sq": "Londra",
      "co": "Londra",
      "tl": "Londres",
      "tk": "London",
      "ab": "Лондон",
      "sa": "लन्डन्",
      "bg": "Лондон",
      "gl": "Londres",
      "el": "Λονδίνο",
      "hr": "London",
      "sl": "London",
      "pa": "ਲੰਡਨ",
      "wa": "Londe",
      "li": "Londe",
      "fy": "Londen",
      "to": "Lonitoni",
      "bi": "London",
      "om": "Landan",
      "su": "London",
      "fo": "London",
      "ru": "Лондон",
      "ta": "இலண்டன்",
      "ps": "لندن",
      "ee": "London",
      "de": "London",
      "es": "Londres",
      "bn": "লন্ডন",
      "cu": "Лондонъ",
      "no": "London",
      "ia": "London",
      "ar": "لندن",
      "ro": "Londra",
      "gd": "Lunnainn",
      "ff": "London",
      "kl": "London",
      "lo": "ລອນດອນ",
      "th": "ลอนดอน",
      "eu": "Londres",
      "nl": "Londen",
      "sr": "Лондон",
      "ja": "ロンドン",
      "my": "လန်ဒန်မြို့",
      "ha": "Landan",
      "sh": "London",
      "oc": "Londres",
      "eo": "Londono",
      "gu": "લંડન",
      "rm": "Londra",
      "nn": "London",
      "ba": "Лондон",
      "be": "Лондан",
      "mk": "Лондон",
      "gn": "Lóndyre",
      "yo": "Lọndọnu",
      "ln": "Lóndɛlɛ",
      "sn": "London",
      "et": "London",
      "vi": "Luân Đôn",
      "sm": "Lonetona",
      "mn": "Лондон",
      "te": "లండన్",
      "tw": "London",
      "id": "London",
      "mi": "Rānana",
      "br": "Londrez",
      "kw": "Loundres",
      "ne": "लन्डन",
      "ht": "Lonn",
      "vo": "London",
      "si": "ලන්ඩන්",
      "lv": "Londona",
      "ny": "London",
      "af": "Londen",
      "or": "ଲଣ୍ଡନ",
      "ky": "Лондон",
      "ce": "Лондон",
      "cy": "Llundain",
      "kk": "Лондон",
      "hy": "Լոնդոն",
      "mr": "लंडन",
      "na": "London",
      "fj": "Lodoni",
      "en": "London",
      "lb": "London",
      "so": "London",
      "jv": "London",
      "sc": "Londra",
      "io": "London",
      "tr": "Londra",
      "da": "London",
      "az": "London",
      "uz": "London",
      "mg": "Lôndôna",
      "sw": "London",
      "bh": "लंदन",
      "lt": "Londonas",
      "zu": "ILondon",
      "wo": "Londar",
      "ca": "Londres",
      "ko": "런던",
      "ml": "ലണ്ടൻ",
      "sk": "Londýn",
      "se": "London",
      "sv": "London",
      "tg": "Лондон",
      "kv": "Лондон",
      "os": "Лондон",
      "av": "Лондон",
      "fa": "لندن",
      "kn": "ಲಂಡನ್",
      "he": "לונדון",
      "ig": "London",
      "tt": "Лондон",
      "ka": "ლონდონი",
      "cs": "Londýn",
      "uk": "Лондон",
      "cv": "Лондон",
      "nv": "Tooh Dineʼé Bikin Haalʼá",
      "sd": "لنڊن",
      "ay": "London",
      "bo": "ལོན་ཊོན།",
      "ie": "London",
      "qu": "London",
      "km": "ឡុងដ៍",
      "an": "Londres",
      "pt": "Londres",
      "feature_name": "London",
      "pl": "Londyn",
      "ku": "London",
      "hu": "London",
      "ms": "London",
      "yi": "לאנדאן",
      "am": "ለንደን",
      "fi": "Lontoo",
      "ascii": "London",
      "gv": "Lunnin",
      "it": "Londra",
      "ga": "Londain",
      "bs": "London",
      "hi": "लंदन",
      "mt": "Londra",
      "ug": "لوندۇن",
      "bm": "London",
      "ur": "علاقہ لندن",
      "zh": "伦敦"
    },
    "lat": 51.5073219,
    "lon": -0.1276474,
    "country": "GB",
    "state": "England"
  },
  {
    "name": "City of London",
    "local_names": {
      "pt": "Cidade de Londres",
      "ru": "Сити",
      "he": "הסיטי של לונדון",
      "es": "City de Londres",
      "ur": "لندن شہر",
      "lt": "Londono Sitis",
      "uk": "Лондонське Сіті",
      "en": "City of London",
      "fr": "Cité de Londres",
      "hi": "सिटी ऑफ़ लंदन",
      "ko": "시티 오브 런던",
      "zh": "倫敦市"
    },
    "lat": 51.5156177,
    "lon": -0.0919983,
    "country": "GB",
    "state": "England"
  },
  {
    "name": "London",
    "local_names": {
      "fa": "لندن",
      "th": "ลอนดอน",
      "ru": "Лондон",
      "hy": "Լոնտոն",
      "ga": "Londain",
      "ka": "ლონდონი",
      "yi": "לאנדאן",
      "fr": "London",
      "be": "Лондан",
      "ko": "런던",
      "ja": "ロンドン",
      "ug": "لوندۇن",
      "cr": "ᓬᐊᐣᑕᐣ",
      "lv": "Landona",
      "iu": "ᓚᓐᑕᓐ",
      "el": "Λόντον",
      "oj": "Baketigweyaang",
      "en": "London",
      "bn": "লন্ডন",
      "he": "לונדון",
      "ar": "لندن",
      "lt": "Londonas"
    },
    "lat": 42.9832406,
    "lon": -81.243372,
    "country": "CA",
    "state": "Ontario"
  },
  {
    "name": "Chelsea",
    "local_names": {
      "da": "Chelsea",
      "en": "Chelsea",
      "uk": "Челсі",
      "zh": "車路士",
      "he": "צ'לסי",
      "ga": "Chelsea",
      "hu": "Chelsea",
      "nl": "Chelsea",
      "fr": "Chelsea",
      "sh": "Chelsea, London",
      "pt": "Chelsea",
      "id": "Chelsea, London",
      "pl": "Chelsea",
      "de": "Chelsea",
      "fa": "چلسی",
      "tr": "Chelsea, Londra",
      "hi": "चेल्सी, लंदन",
      "es": "Chelsea",
      "ur": "چیلسی، لندن",
      "vi": "Chelsea, Luân Đôn",
      "ko": "첼시",
      "sk": "Chelsea",
      "af": "Chelsea, Londen",
      "el": "Τσέλσι",
      "ru": "Челси",
      "eu": "Chelsea",
      "az": "Çelsi",
      "sv": "Chelsea, London",
      "it": "Chelsea",
      "ar": "تشيلسي",
      "ja": "チェルシー",
      "et": "Chelsea",
      "no": "Chelsea"
    },
    "lat": 51.4875167,
    "lon": -0.1687007,
    "country": "GB",
    "state": "England"
  },
  {
    "name": "London",
    "lat": 37.1289771,
    "lon": -84.0832646,
    "country": "US",
    "state": "Kentucky"
  }
]